/*
 * sc_gl_enum.h — catálogo completo de opcodes GLES 3.0 + 3.1 + 3.2.
 *
 * Cada opcode identifica una función GL. Los argumentos y valores de retorno
 * se serializan en el orden exacto de la firma oficial (GLES3/gl32.h).
 *
 * Los punteros a datos se mandan como [u32 nbytes][bytes]; el tamaño lo
 * conoce el emisor (shim) porque conoce la firma real y las longitudes
 * asociadas (count de elementos por sizeof del tipo). El receptor (daemon)
 * también conoce la firma real vía GLES headers y reconstruye los argumentos
 * en el mismo orden. No hay ambigüedad de tipo ni de tamaño.
 *
 * Los punteros a datos de salida (glGet*, glReadPixels, glMapBufferRange)
 * solo aparecen en llamadas SC_OP_GL_SYNC; el shim reserva el buffer del
 * usuario, el daemon escribe la respuesta en bytes, el shim la copia al
 * buffer del usuario. No hay manera de escribir directamente en el buffer
 * del cliente desde el daemon.
 *
 * Los handles opacos (GLsync, EGLImage) se transportan como u64.
 */
#ifndef SC_GL_ENUM_H
#define SC_GL_ENUM_H

enum sc_gl_op {
    /* ---- ES 2.0 / 3.0 ---- */
    SC_GL_glActiveTexture = 0x80000000u + 0,
    SC_GL_glAttachShader,
    SC_GL_glBindAttribLocation,
    SC_GL_glBindBuffer,
    SC_GL_glBindFramebuffer,
    SC_GL_glBindRenderbuffer,
    SC_GL_glBindTexture,
    SC_GL_glBlendColor,
    SC_GL_glBlendEquation,
    SC_GL_glBlendEquationSeparate,
    SC_GL_glBlendFunc,
    SC_GL_glBlendFuncSeparate,
    SC_GL_glBufferData,
    SC_GL_glBufferSubData,
    SC_GL_glCheckFramebufferStatus,
    SC_GL_glClear,
    SC_GL_glClearColor,
    SC_GL_glClearDepthf,
    SC_GL_glClearStencil,
    SC_GL_glColorMask,
    SC_GL_glCompileShader,
    SC_GL_glCompressedTexImage2D,
    SC_GL_glCompressedTexSubImage2D,
    SC_GL_glCopyTexImage2D,
    SC_GL_glCopyTexSubImage2D,
    SC_GL_glCreateProgram,
    SC_GL_glCreateShader,
    SC_GL_glCullFace,
    SC_GL_glDeleteBuffers,
    SC_GL_glDeleteFramebuffers,
    SC_GL_glDeleteProgram,
    SC_GL_glDeleteRenderbuffers,
    SC_GL_glDeleteShader,
    SC_GL_glDeleteTextures,
    SC_GL_glDepthFunc,
    SC_GL_glDepthMask,
    SC_GL_glDepthRangef,
    SC_GL_glDetachShader,
    SC_GL_glDisable,
    SC_GL_glDisableVertexAttribArray,
    SC_GL_glDrawArrays,
    SC_GL_glDrawElements,
    SC_GL_glEnable,
    SC_GL_glEnableVertexAttribArray,
    SC_GL_glFinish,
    SC_GL_glFlush,
    SC_GL_glFramebufferRenderbuffer,
    SC_GL_glFramebufferTexture2D,
    SC_GL_glFrontFace,
    SC_GL_glGenBuffers,
    SC_GL_glGenerateMipmap,
    SC_GL_glGenFramebuffers,
    SC_GL_glGenRenderbuffers,
    SC_GL_glGenTextures,
    SC_GL_glGetActiveAttrib,
    SC_GL_glGetActiveUniform,
    SC_GL_glGetAttachedShaders,
    SC_GL_glGetAttribLocation,
    SC_GL_glGetBooleanv,
    SC_GL_glGetBufferParameteriv,
    SC_GL_glGetError,
    SC_GL_glGetFloatv,
    SC_GL_glGetFramebufferAttachmentParameteriv,
    SC_GL_glGetIntegerv,
    SC_GL_glGetProgramInfoLog,
    SC_GL_glGetProgramiv,
    SC_GL_glGetRenderbufferParameteriv,
    SC_GL_glGetShaderInfoLog,
    SC_GL_glGetShaderiv,
    SC_GL_glGetShaderPrecisionFormat,
    SC_GL_glGetShaderSource,
    SC_GL_glGetString,
    SC_GL_glGetTexParameterfv,
    SC_GL_glGetTexParameteriv,
    SC_GL_glGetUniformfv,
    SC_GL_glGetUniformiv,
    SC_GL_glGetUniformLocation,
    SC_GL_glGetVertexAttribfv,
    SC_GL_glGetVertexAttribiv,
    SC_GL_glGetVertexAttribPointerv,
    SC_GL_glHint,
    SC_GL_glIsBuffer,
    SC_GL_glIsEnabled,
    SC_GL_glIsFramebuffer,
    SC_GL_glIsProgram,
    SC_GL_glIsRenderbuffer,
    SC_GL_glIsShader,
    SC_GL_glIsTexture,
    SC_GL_glLineWidth,
    SC_GL_glLinkProgram,
    SC_GL_glPixelStorei,
    SC_GL_glPolygonOffset,
    SC_GL_glReadPixels,
    SC_GL_glReleaseShaderCompiler,
    SC_GL_glRenderbufferStorage,
    SC_GL_glSampleCoverage,
    SC_GL_glScissor,
    SC_GL_glShaderBinary,
    SC_GL_glShaderSource,
    SC_GL_glStencilFunc,
    SC_GL_glStencilFuncSeparate,
    SC_GL_glStencilMask,
    SC_GL_glStencilMaskSeparate,
    SC_GL_glStencilOp,
    SC_GL_glStencilOpSeparate,
    SC_GL_glTexImage2D,
    SC_GL_glTexParameterf,
    SC_GL_glTexParameterfv,
    SC_GL_glTexParameteri,
    SC_GL_glTexParameteriv,
    SC_GL_glTexSubImage2D,
    SC_GL_glUniform1f,
    SC_GL_glUniform1fv,
    SC_GL_glUniform1i,
    SC_GL_glUniform1iv,
    SC_GL_glUniform2f,
    SC_GL_glUniform2fv,
    SC_GL_glUniform2i,
    SC_GL_glUniform2iv,
    SC_GL_glUniform3f,
    SC_GL_glUniform3fv,
    SC_GL_glUniform3i,
    SC_GL_glUniform3iv,
    SC_GL_glUniform4f,
    SC_GL_glUniform4fv,
    SC_GL_glUniform4i,
    SC_GL_glUniform4iv,
    SC_GL_glUniformMatrix2fv,
    SC_GL_glUniformMatrix3fv,
    SC_GL_glUniformMatrix4fv,
    SC_GL_glUseProgram,
    SC_GL_glValidateProgram,
    SC_GL_glVertexAttrib1f,
    SC_GL_glVertexAttrib1fv,
    SC_GL_glVertexAttrib2f,
    SC_GL_glVertexAttrib2fv,
    SC_GL_glVertexAttrib3f,
    SC_GL_glVertexAttrib3fv,
    SC_GL_glVertexAttrib4f,
    SC_GL_glVertexAttrib4fv,
    SC_GL_glVertexAttribPointer,
    SC_GL_glViewport,

    /* ---- ES 3.0 ---- */
    SC_GL_glReadBuffer,
    SC_GL_glDrawRangeElements,
    SC_GL_glTexImage3D,
    SC_GL_glTexSubImage3D,
    SC_GL_glCopyTexSubImage3D,
    SC_GL_glCompressedTexImage3D,
    SC_GL_glCompressedTexSubImage3D,
    SC_GL_glGenQueries,
    SC_GL_glDeleteQueries,
    SC_GL_glIsQuery,
    SC_GL_glBeginQuery,
    SC_GL_glEndQuery,
    SC_GL_glGetQueryiv,
    SC_GL_glGetQueryObjectuiv,
    SC_GL_glUnmapBuffer,
    SC_GL_glGetBufferPointerv,
    SC_GL_glDrawBuffers,
    SC_GL_glUniformMatrix2x3fv,
    SC_GL_glUniformMatrix3x2fv,
    SC_GL_glUniformMatrix2x4fv,
    SC_GL_glUniformMatrix4x2fv,
    SC_GL_glUniformMatrix3x4fv,
    SC_GL_glUniformMatrix4x3fv,
    SC_GL_glBlitFramebuffer,
    SC_GL_glRenderbufferStorageMultisample,
    SC_GL_glFramebufferTextureLayer,
    SC_GL_glMapBufferRange,
    SC_GL_glFlushMappedBufferRange,
    SC_GL_glBindVertexArray,
    SC_GL_glDeleteVertexArrays,
    SC_GL_glGenVertexArrays,
    SC_GL_glIsVertexArray,
    SC_GL_glGetIntegeri_v,
    SC_GL_glBeginTransformFeedback,
    SC_GL_glEndTransformFeedback,
    SC_GL_glBindBufferRange,
    SC_GL_glBindBufferBase,
    SC_GL_glTransformFeedbackVaryings,
    SC_GL_glGetTransformFeedbackVarying,
    SC_GL_glVertexAttribIPointer,
    SC_GL_glGetVertexAttribIiv,
    SC_GL_glGetVertexAttribIuiv,
    SC_GL_glVertexAttribI4i,
    SC_GL_glVertexAttribI4ui,
    SC_GL_glVertexAttribI4iv,
    SC_GL_glVertexAttribI4uiv,
    SC_GL_glGetUniformuiv,
    SC_GL_glGetFragDataLocation,
    SC_GL_glUniform1ui,
    SC_GL_glUniform2ui,
    SC_GL_glUniform3ui,
    SC_GL_glUniform4ui,
    SC_GL_glUniform1uiv,
    SC_GL_glUniform2uiv,
    SC_GL_glUniform3uiv,
    SC_GL_glUniform4uiv,
    SC_GL_glClearBufferiv,
    SC_GL_glClearBufferuiv,
    SC_GL_glClearBufferfv,
    SC_GL_glClearBufferfi,
    SC_GL_glGetStringi,
    SC_GL_glCopyBufferSubData,
    SC_GL_glGetUniformIndices,
    SC_GL_glGetActiveUniformsiv,
    SC_GL_glGetUniformBlockIndex,
    SC_GL_glGetActiveUniformBlockiv,
    SC_GL_glGetActiveUniformBlockName,
    SC_GL_glUniformBlockBinding,
    SC_GL_glDrawArraysInstanced,
    SC_GL_glDrawElementsInstanced,
    SC_GL_glFenceSync,
    SC_GL_glIsSync,
    SC_GL_glDeleteSync,
    SC_GL_glClientWaitSync,
    SC_GL_glWaitSync,
    SC_GL_glGetInteger64v,
    SC_GL_glGetSynciv,
    SC_GL_glGetInteger64i_v,
    SC_GL_glGetBufferParameteri64v,
    SC_GL_glGenSamplers,
    SC_GL_glDeleteSamplers,
    SC_GL_glIsSampler,
    SC_GL_glBindSampler,
    SC_GL_glSamplerParameteri,
    SC_GL_glSamplerParameteriv,
    SC_GL_glSamplerParameterf,
    SC_GL_glSamplerParameterfv,
    SC_GL_glGetSamplerParameteriv,
    SC_GL_glGetSamplerParameterfv,
    SC_GL_glVertexAttribDivisor,
    SC_GL_glBindTransformFeedback,
    SC_GL_glDeleteTransformFeedbacks,
    SC_GL_glGenTransformFeedbacks,
    SC_GL_glIsTransformFeedback,
    SC_GL_glPauseTransformFeedback,
    SC_GL_glResumeTransformFeedback,
    SC_GL_glDrawTransformFeedback,
    SC_GL_glInvalidateFramebuffer,
    SC_GL_glInvalidateSubFramebuffer,

    /* ---- ES 3.1 ---- */
    SC_GL_glDispatchCompute,
    SC_GL_glDispatchComputeIndirect,
    SC_GL_glFramebufferParameteri,
    SC_GL_glGetFramebufferParameteriv,
    SC_GL_glGetInternalformati64v,
    SC_GL_glInvalidateTexSubImage,
    SC_GL_glInvalidateTexImage,
    SC_GL_glInvalidateBufferSubData,
    SC_GL_glInvalidateBufferData,
    SC_GL_glGetProgramInterfaceiv,
    SC_GL_glGetProgramResourceIndex,
    SC_GL_glGetProgramResourceName,
    SC_GL_glGetProgramResourceiv,
    SC_GL_glGetProgramResourceLocation,
    SC_GL_glGetProgramResourceLocationIndex,
    SC_GL_glShaderStorageBlockBinding,
    SC_GL_glTexBufferRange,
    SC_GL_glTexStorage2DMultisample,
    SC_GL_glTexStorage3DMultisample,
    SC_GL_glTextureView,
    SC_GL_glBindImageTexture,
    SC_GL_glMemoryBarrier,
    SC_GL_glMemoryBarrierByRegion,
    SC_GL_glGetMultisamplefv,
    SC_GL_glSampleMaski,
    SC_GL_glTexStorage2D,
    SC_GL_glTexStorage3D,
    SC_GL_glGetTexLevelParameteriv,
    SC_GL_glGetTexLevelParameterfv,
    SC_GL_glBindVertexBuffer,
    SC_GL_glVertexAttribFormat,
    SC_GL_glVertexAttribIFormat,
    SC_GL_glVertexAttribBinding,
    SC_GL_glVertexBindingDivisor,

    /* ---- ES 3.2 ---- */
    SC_GL_glBlendBarrier,
    SC_GL_glCopyImageSubData,
    SC_GL_glDebugMessageControl,
    SC_GL_glDebugMessageInsert,
    SC_GL_glDebugMessageCallback,
    SC_GL_glGetDebugMessageLog,
    SC_GL_glPushDebugGroup,
    SC_GL_glPopDebugGroup,
    SC_GL_glObjectLabel,
    SC_GL_glGetObjectLabel,
    SC_GL_glObjectPtrLabel,
    SC_GL_glGetObjectPtrLabel,
    SC_GL_glGetPointerv,
    SC_GL_glEnablei,
    SC_GL_glDisablei,
    SC_GL_glBlendEquationi,
    SC_GL_glBlendEquationSeparatei,
    SC_GL_glBlendFunci,
    SC_GL_glBlendFuncSeparatei,
    SC_GL_glColorMaski,
    SC_GL_glIsEnabledi,
    SC_GL_glDrawElementsBaseVertex,
    SC_GL_glDrawRangeElementsBaseVertex,
    SC_GL_glDrawElementsInstancedBaseVertex,
    SC_GL_glDrawArraysIndirect,
    SC_GL_glDrawElementsIndirect,
    SC_GL_glFramebufferTexture,
    SC_GL_glPrimitiveBoundingBox,
    SC_GL_glGetGraphicsResetStatus,
    SC_GL_glReadnPixels,
    SC_GL_glGetnUniformfv,
    SC_GL_glGetnUniformiv,
    SC_GL_glGetnUniformuiv,
    SC_GL_glMinSampleShading,
    SC_GL_glPatchParameteri,
    SC_GL_glTexParameterIiv,
    SC_GL_glTexParameterIuiv,
    SC_GL_glGetTexParameterIiv,
    SC_GL_glGetTexParameterIuiv,
    SC_GL_glSamplerParameterIiv,
    SC_GL_glSamplerParameterIuiv,
    SC_GL_glGetSamplerParameterIiv,
    SC_GL_glGetSamplerParameterIuiv,
    SC_GL_glGetQueryObjectiv,
    SC_GL_glGetQueryObjecti64v,
    SC_GL_glGetQueryObjectui64v,
    SC_GL_glGetQueryBufferObjectiv,
    SC_GL_glGetQueryBufferObjectuiv,
    SC_GL_glGetQueryBufferObjecti64v,
    SC_GL_glGetQueryBufferObjectui64v,

    /* ---- [ADD] core ES 3.2 faltantes ---- */
    SC_GL_glGetInternalformativ,
    SC_GL_glTexBuffer,

    /* ---- extensiones ES 2.0/3.0 ampliamente usadas ---- */
    SC_GL_glGetProgramBinary,
    SC_GL_glProgramBinary,
    SC_GL_glProgramParameteri,

    /* ---- extensiones EGL para Android/Mali ---- */
    SC_GL_glEGLImageTargetTexture2DOES,
    SC_GL_glEGLImageTargetRenderbufferStorageOES,
    SC_GL_glBlendEquationOES,
    SC_GL_glBlendEquationSeparateOES,
    SC_GL_glBlendFuncSeparateOES,
    SC_GL_glBlendFuncSeparateiOES,
    SC_GL_glBlendEquationiOES,
    SC_GL_glBlendEquationSeparateiOES,
    SC_GL_glBlendFunciOES,
    SC_GL_glDrawArraysInstancedANGLE,
    SC_GL_glDrawElementsInstancedANGLE,
    SC_GL_glVertexAttribDivisorANGLE,
    SC_GL_glGenVertexArraysOES,
    SC_GL_glBindVertexArrayOES,
    SC_GL_glDeleteVertexArraysOES,
    SC_GL_glIsVertexArrayOES,
    SC_GL_glRenderbufferStorageMultisampleANGLE,
    SC_GL_glFramebufferTexture2DMultisampleEXT,
    SC_GL_glFramebufferTextureMultiviewOVR,
    SC_GL_glTexStorage2DEXT,
    SC_GL_glTexStorage3DEXT,
    SC_GL_glTextureStorage2DEXT,
    SC_GL_glTextureStorage3DEXT,
    SC_GL_glCopyImageSubDataEXT,
    SC_GL_glDiscardFramebufferEXT,
    SC_GL_glMultiDrawArraysEXT,
    SC_GL_glMultiDrawElementsEXT,
    SC_GL_glMultiDrawArraysIndirectEXT,
    SC_GL_glMultiDrawElementsIndirectEXT,
    SC_GL_glDebugMessageCallbackKHR,
    SC_GL_glDebugMessageControlKHR,
    SC_GL_glDebugMessageInsertKHR,
    SC_GL_glGetDebugMessageLogKHR,
    SC_GL_glPushDebugGroupKHR,
    SC_GL_glPopDebugGroupKHR,
    SC_GL_glObjectLabelKHR,
    SC_GL_glGetObjectLabelKHR,
    SC_GL_glObjectPtrLabelKHR,
    SC_GL_glGetObjectPtrLabelKHR,
    SC_GL_glGetPointervKHR,
    SC_GL_glQueryCounterEXT,
    SC_GL_glGetQueryObjecti64vEXT,
    SC_GL_glGetQueryObjectui64vEXT,
    SC_GL_glGetQueryObjectivEXT,
    SC_GL_glGetQueryObjectuivEXT,
    SC_GL_glBlendBarrierKHR,
    SC_GL_glBlendBarrierNV,
    SC_GL_glTexBufferEXT,
    SC_GL_glTexBufferOES,
    SC_GL_glTexBufferRangeEXT,
    SC_GL_glTexBufferRangeOES,
    SC_GL_glFramebufferTexture2DDownsampleIMG,
    SC_GL_glFramebufferTextureLayerDownsampleIMG,
    SC_GL_glFramebufferTextureMultisampleMultiviewOVR,
    /* ---- [ADD] sentinel para conteo robusto ---- */
    SC_GL_OP_SENTINEL,
};
#undef SC_GL_OP_COUNT
#define SC_GL_OP_COUNT (SC_GL_OP_SENTINEL - SC_GL_glActiveTexture)

/* [ADD] Eventos del protocolo que no corresponden a llamadas GL.
 * Viajan dentro de SC_OP_GL_SYNC o SC_OP_GL_BATCH según tengan respuesta o no. */
enum sc_gl_event {
    SC_GL_EV_MAP_WRITEBACK  = 0x8000F000u, /* cliente -> daemon: bytes escritos en rango mapeado */
    SC_GL_EV_DEBUG_CB_REG   = 0x8000F001u, /* cliente -> daemon: registrar callback (id local) */
    SC_GL_EV_DEBUG_CB_UNREG = 0x8000F002u, /* cliente -> daemon */
    SC_GL_EV_DEBUG_CB_FIRE  = 0x8000F003u, /* daemon -> cliente: disparar callback registrado */
};

#endif /* SC_GL_ENUM_H */
